import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI. 
// You can regenerate it by running `appwrite types -l ts ./src/utils/types.ts`.

// Made so it wasn't an enum by ChatGPT
export const ReportsTypeOfReport = {
    DETAILED: "Detailed",
    UN_DETAILED: "UnDetailed",
} as const;

export type ReportsTypeOfReport =
    typeof ReportsTypeOfReport[keyof typeof ReportsTypeOfReport];

// Made so it wasn't an enum by ChatGPT
export const ReportsReportStatus = {
    APPROVED: "Approved",
    DISAPPROVED: "Disapproved",
    SUSPECT: "Suspect",
    ASSUMED: "Assumed",
} as const;

export type ReportsReportStatus =
    typeof ReportsReportStatus[keyof typeof ReportsReportStatus];


export type Groups = Models.Row & {
    groupName: string;
    isActive: boolean;
    suspectCount: number | null;
    reporterCount: number | null;
}

export type Suspects = Models.Row & {
    firstName: string;
    lastName: string | null;
    title: string;
    groupID: Groups;
    avatarURL: string | null;
}

export type Reporters = Models.Row & {
    ipAddress: string;
    isActive: boolean;
    reportCount: number;
    groupsID: Groups[];
}

export type Reports = Models.Row & {
    reportDate: string;
    reporterID: Reporters;
    suspectID: Suspects;
    slangID: Slang;
    typeOfReport: ReportsTypeOfReport;
    reportStatus: ReportsReportStatus;
}

export type Slang = Models.Row & {
    word: string;
    definition: string | null;
    isActive: boolean;
    useFrequency: number | null;
    originYear: string | null;
    exampleUsage: string | null;
    partOfSpeech: string[] | null;
}

export type Subgroups = Models.Row & {
    title: string;
    suspectsID: Suspects[];
    groupID: Groups;
}
